import { GroupButtonListType } from "@/components/common/buttons/buttonTypes";
import { SkillCardType } from "@/components/common/cards/cardTypes";

export const SKILL_LIST: SkillCardType[] = [
  {
    id: 1,
    name: "Javascript",
    logo: "/images/icons/javascript.png",
    experience: "4yrs 2m",
    category: "language",
  },
  {
    id: 2,
    name: "Typescript",
    logo: "/images/icons/typescript.png",
    experience: "2yrs",
    category: "language",
  },
  {
    id: 3,
    name: "Reactjs",
    logo: "/images/icons/reactjs.png",
    experience: "3yrs 8m",
    category: "framework",
  },
  {
    id: 4,
    name: "Nextjs",
    logo: "/images/icons/nextjs.png",
    experience: "1yr 6m",
    category: "framework",
  },
  {
    id: 5,
    name: "Redux",
    logo: "/images/icons/redux.png",
    experience: "2yrs",
    category: "language",
  },
  {
    id: 6,
    name: "Apollo Graphql",
    logo: "/images/icons/apollo-graphql.png",
    experience: "1yr 2m",
    category: "other",
  },
  {
    id: 7,
    name: "React Query",
    logo: "/images/icons/react-query.png",
    experience: "1yr",
    category: "other",
  },
  {
    id: 8,
    name: "Material UI",
    logo: "/images/icons/material-ui.png",
    experience: "2yrs 4m",
    category: "framework",
  },
  {
    id: 9,
    name: "Tailwind CSS",
    logo: "/images/icons/tailwind.png",
    experience: "3yrs",
    category: "framework",
  },
  {
    id: 10,
    name: "React Hook Form",
    logo: "/images/icons/react-hook-form.png",
    experience: "3yrs",
    category: "other",
  },
  {
    id: 11,
    name: "Apex Chart",
    logo: "/images/icons/apex-chart.png",
    experience: "3yrs",
    category: "other",
  },
  {
    id: 12,
    name: "AntD",
    logo: "/images/icons/antd.png",
    experience: "1yr 7m",
    category: "framework",
  },
  {
    id: 13,
    name: "Git",
    logo: "/images/icons/git.png",
    experience: "1yr 2m",
    category: "tool",
  },
  {
    id: 14,
    name: "HTML5",
    logo: "/images/icons/html5.png",
    experience: "1yr 2m",
    category: "language",
  },
  {
    id: 15,
    name: "CSS3",
    logo: "/images/icons/css3.png",
    experience: "1yr 2m",
    category: "language",
  },
  {
    id: 16,
    name: "Jquery",
    logo: "/images/icons/jquery.png",
    experience: "1yr 2m",
    category: "framework",
  },
  {
    id: 17,
    name: "SCSS",
    logo: "/images/icons/scss.png",
    experience: "1yr 2m",
    category: "other",
  },
  {
    id: 18,
    name: "Bootstrap",
    logo: "/images/icons/bootstrap-5.png",
    experience: "1yr 2m",
    category: "framework",
  },
  {
    id: 19,
    name: "Yarn",
    logo: "/images/icons/yarn.png",
    experience: "1yr 2m",
    category: "tool",
  },
  {
    id: 20,
    name: "NPM",
    logo: "/images/icons/npm.png",
    experience: "1yr 2m",
    category: "tool",
  },
  {
    id: 21,
    name: "REST",
    logo: "/images/icons/rest-api.jpg",
    experience: "1yr 2m",
    category: "other",
  },
  {
    id: 22,
    name: "JSON",
    logo: "/images/icons/json.png",
    experience: "1yr 2m",
    category: "other",
  },
];

export const BUTTON_LIST: GroupButtonListType[] = [
  { id: 1, title: "All", value: "all" },
  { id: 2, title: "Languages", value: "language" },
  { id: 3, title: "Frameworks", value: "framework" },
  { id: 4, title: "Tools", value: "tool" },
  { id: 5, title: "Others", value: "other" },
];
